CREATE TABLE dealerships (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    CONSTRAINT dealerships_pkey PRIMARY KEY (id),
    CONSTRAINT dealerships_id_positive CHECK (id > 0),
    CONSTRAINT dealerships_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT dealerships_name_unique UNIQUE (name)
);

CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    full_name text NOT NULL,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_id_positive CHECK (id > 0),
    CONSTRAINT customers_full_name_not_blank CHECK (btrim(full_name) <> '')
);

CREATE TABLE vehicles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    registration_number text NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    CONSTRAINT vehicles_pkey PRIMARY KEY (id),
    CONSTRAINT vehicles_id_positive CHECK (id > 0),
    CONSTRAINT vehicles_customer_fk
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT vehicles_registration_not_blank CHECK (btrim(registration_number) <> ''),
    CONSTRAINT vehicles_make_not_blank CHECK (btrim(make) <> ''),
    CONSTRAINT vehicles_model_not_blank CHECK (btrim(model) <> ''),
    CONSTRAINT vehicles_registration_unique UNIQUE (registration_number),
    CONSTRAINT vehicles_id_customer_unique UNIQUE (id, customer_id)
);

CREATE TABLE service_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    duration_minutes integer NOT NULL,
    CONSTRAINT service_types_pkey PRIMARY KEY (id),
    CONSTRAINT service_types_id_positive CHECK (id > 0),
    CONSTRAINT service_types_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT service_types_duration_positive CHECK (duration_minutes > 0),
    CONSTRAINT service_types_name_unique UNIQUE (name)
);

CREATE TABLE technicians (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dealership_id bigint NOT NULL,
    full_name text NOT NULL,
    CONSTRAINT technicians_pkey PRIMARY KEY (id),
    CONSTRAINT technicians_id_positive CHECK (id > 0),
    CONSTRAINT technicians_dealership_fk
        FOREIGN KEY (dealership_id) REFERENCES dealerships (id) ON DELETE RESTRICT,
    CONSTRAINT technicians_full_name_not_blank CHECK (btrim(full_name) <> ''),
    CONSTRAINT technicians_dealership_name_unique UNIQUE (dealership_id, full_name),
    CONSTRAINT technicians_id_dealership_unique UNIQUE (id, dealership_id)
);

CREATE TABLE technician_qualifications (
    technician_id bigint NOT NULL,
    service_type_id bigint NOT NULL,
    CONSTRAINT technician_qualifications_pkey
        PRIMARY KEY (technician_id, service_type_id),
    CONSTRAINT technician_qualifications_technician_fk
        FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE,
    CONSTRAINT technician_qualifications_service_type_fk
        FOREIGN KEY (service_type_id) REFERENCES service_types (id) ON DELETE RESTRICT
);

CREATE TABLE service_bays (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dealership_id bigint NOT NULL,
    name text NOT NULL,
    CONSTRAINT service_bays_pkey PRIMARY KEY (id),
    CONSTRAINT service_bays_id_positive CHECK (id > 0),
    CONSTRAINT service_bays_dealership_fk
        FOREIGN KEY (dealership_id) REFERENCES dealerships (id) ON DELETE RESTRICT,
    CONSTRAINT service_bays_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT service_bays_dealership_name_unique UNIQUE (dealership_id, name),
    CONSTRAINT service_bays_id_dealership_unique UNIQUE (id, dealership_id)
);

CREATE TABLE appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    dealership_id bigint NOT NULL,
    service_type_id bigint NOT NULL,
    technician_id bigint NOT NULL,
    service_bay_id bigint NOT NULL,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'CONFIRMED',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT appointments_pkey PRIMARY KEY (id),
    CONSTRAINT appointments_id_positive CHECK (id > 0),
    CONSTRAINT appointments_customer_fk
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT appointments_vehicle_customer_fk
        FOREIGN KEY (vehicle_id, customer_id)
        REFERENCES vehicles (id, customer_id) ON DELETE RESTRICT,
    CONSTRAINT appointments_dealership_fk
        FOREIGN KEY (dealership_id) REFERENCES dealerships (id) ON DELETE RESTRICT,
    CONSTRAINT appointments_service_type_fk
        FOREIGN KEY (service_type_id) REFERENCES service_types (id) ON DELETE RESTRICT,
    CONSTRAINT appointments_technician_dealership_fk
        FOREIGN KEY (technician_id, dealership_id)
        REFERENCES technicians (id, dealership_id) ON DELETE RESTRICT,
    CONSTRAINT appointments_technician_qualification_fk
        FOREIGN KEY (technician_id, service_type_id)
        REFERENCES technician_qualifications (technician_id, service_type_id)
        ON DELETE RESTRICT,
    CONSTRAINT appointments_bay_dealership_fk
        FOREIGN KEY (service_bay_id, dealership_id)
        REFERENCES service_bays (id, dealership_id) ON DELETE RESTRICT,
    CONSTRAINT appointments_interval_positive CHECK (end_time > start_time),
    CONSTRAINT appointments_status_confirmed CHECK (status = 'CONFIRMED')
);

CREATE INDEX idx_vehicles_customer
    ON vehicles (customer_id, id);

CREATE INDEX idx_technicians_dealership
    ON technicians (dealership_id, id);

CREATE INDEX idx_technician_qualifications_service
    ON technician_qualifications (service_type_id, technician_id);

CREATE INDEX idx_service_bays_dealership
    ON service_bays (dealership_id, id);

CREATE INDEX idx_appointments_technician_interval
    ON appointments (dealership_id, technician_id, start_time, end_time);

CREATE INDEX idx_appointments_bay_interval
    ON appointments (dealership_id, service_bay_id, start_time, end_time);
